name: Reset pending auto updates

on: workflow_dispatch

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - id: detect_auto_updates
      run: python scripts/detect_auto_updates.py auto-update-
    - name: Delete auto-update-* branches
      uses: dawidd6/action-delete-branch@v3
      with:
        branches: ${{ steps.detect_auto_updates.outputs.branches }}
        prefix: auto-update-
    - id: detect_auto_updates_previews
      run: python scripts/detect_auto_updates.py gh-pages-auto-update-
    - name: Delete gh-pages-auto-update-* branches
      uses: dawidd6/action-delete-branch@v3
      with:
        branches: ${{ steps.detect_auto_updates_previews.outputs.branches }}
        prefix: gh-pages-auto-update-
